# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

TARG=github.com/droundy/goadmin/ago/compile

GOFILES=\
        compile.go\

include $(GOROOT)/src/Make.pkg
