# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=github.com/droundy/goadmin/crypt

GOFILES=\
        crypt.go\

include $(GOROOT)/src/Make.pkg
